DSW-I_CL2_BLAS_GALICIA_JUAN_RAMIRO/Controllers/DiscoSolidoController.cs
using DSW_I_CL2_BLAS_GALICIA_JUAN_RAMIRO.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.Reflection;

namespace DSW_I_CL2_BLAS_GALICIA_JUAN_RAMIRO.Controllers
{
    public class DiscoSolidoController : Controller
    {

        public readonly IConfiguration _config;

        public DiscoSolidoController(IConfiguration IConfig)
        {
            _config = IConfig;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult DiscoSolido()
        {
            return View();
        }

        public IActionResult Calcular(ClassCalcular model)
        {
            string mensaje = "";
            const int capacidadCdMb = 700;
            const int capacidadGbMb = 1024;

            int capacidadTotalMb = model.CapaDiscoGB * capacidadGbMb;
            int cdsNecesarios = (int)Math.Ceiling((double)capacidadTotalMb / capacidadCdMb);

            model.CapaCdMB = capacidadTotalMb;
            model.TotalCds = cdsNecesarios;

            using (SqlConnection cn = new SqlConnection(_config["ConnectionStrings:cn"]))

            {
                try
                {
                    SqlCommand cmd = new SqlCommand("sp_guardar_cdsblasgalicia", cn);
                    cn.Open();

                    cmd.CommandType = System.Data.CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@cliente", model.Cliente);
                    cmd.Parameters.AddWithValue("@CapaDisco", model.CapaDiscoGB);
                    cmd.Parameters.AddWithValue("@CapaCds", model.CapaCdMB);
                    cmd.Parameters.AddWithValue("@TotalCds", model.TotalCds);

                    int c = cmd.ExecuteNonQuery();
                    if (c > 0)
                    {
                        mensaje = $"Registro insertado correctamente. Filas afectadas: {c}";
                    }
                    else
                    {
                        mensaje = "No se insertaron filas. Revisa el procedimiento almacenado.";
                    }
                }
                catch (Exception ex)
                {
                    mensaje = $"Error: {ex.Message}";
                    throw;
                }

            }
            ViewBag.mensaje = mensaje;

            return View("Resultado", model);
            //return RedirectToAction("ListadoCalculo", "DiscoSolido");
        }

        IEnumerable<ClassCalcular> Calculos()
        {
            List<ClassCalcular> calculos = new List<ClassCalcular>();
            using (SqlConnection cn = new SqlConnection(_config["ConnectionStrings:cn"]))
            {
                cn.Open();
                SqlCommand cmd = new SqlCommand("sp_listar_cdsblasgalicia", cn);
                SqlDataReader dr = cmd.ExecuteReader();

                while (dr.Read())
                {
                    calculos.Add(new ClassCalcular
                    {
                        Idcd = dr.GetInt32(0),
                        Cliente = dr.GetString(1),
                        CapaDiscoGB = dr.GetInt32(2),
                        CapaCdMB = dr.GetInt32(3),
                        TotalCds = dr.GetInt32(4)
                    });
                }

            }
            return calculos;
        }

        public async Task<IActionResult> ListadoCalculos(int p)
        {
            int nr = 5;

            int tr = Calculos().Count();
            int paginas = nr % tr > 0 ? tr / nr + 1 : tr / nr;
            ViewBag.paginas = paginas;

            return View(await Task.Run(() => Calculos().Skip(p * nr).Take(nr)));
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ClassCalcular editarCalculo = new ClassCalcular();
            using (SqlConnection cn = new SqlConnection(_config["ConnectionStrings:cn"]))
            {
                SqlCommand cmd = new SqlCommand("sp_buscar_cdsblasgalicia @Idcd", cn);
                cmd.Parameters.AddWithValue("@Idcd", id);
                cn.Open();

                using (SqlDataReader dr = cmd.ExecuteReader())
                {
                    if (dr.Read())
                    {
                        editarCalculo.Idcd = dr.GetInt32(0);
                        editarCalculo.Cliente = dr.GetString(1);
                        editarCalculo.CapaDiscoGB = dr.GetInt32(2);
                    }

                }
            }
            return View(editarCalculo);
        }

        [HttpPost, ActionName("Edit")]
        public IActionResult Edit_Post(ClassCalcular classCalcular)
        {
            string cli = classCalcular.Cliente;
            string mensaje = "";

            const int capacidadCdMb = 700;
            const int capacidadGbMb = 1024;

            int capacidadTotalMb = classCalcular.CapaDiscoGB * capacidadGbMb;
            int cdsNecesarios = (int)Math.Ceiling((double)capacidadTotalMb / capacidadCdMb);

            classCalcular.CapaCdMB = capacidadTotalMb;
            classCalcular.TotalCds = cdsNecesarios;

            using (SqlConnection cn = new SqlConnection(_config["ConnectionStrings:cn"]))

            {
                try
                {
                    SqlCommand cmd = new SqlCommand("sp_actualizar_cdblasgalicia", cn);
                    cn.Open();

                    cmd.CommandType = System.Data.CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@Idcd", classCalcular.Idcd);
                    cmd.Parameters.AddWithValue("@cliente", classCalcular.Cliente);
                    cmd.Parameters.AddWithValue("@CapaDisco", classCalcular.CapaDiscoGB);
                    cmd.Parameters.AddWithValue("@CapaCds", classCalcular.CapaCdMB);
                    cmd.Parameters.AddWithValue("@TotalCds", classCalcular.TotalCds);

                    int c = cmd.ExecuteNonQuery();
                    if (c > 0)
                    {
                        mensaje = $"Registro actualizado correctamente. Filas afectadas: {c}";
                    }
                    else
                    {
                        mensaje = "No se actualizaron filas. Revisa el procedimiento almacenado.";
                    }
                }
                catch (Exception ex)
                {
                    mensaje = $"Error: {ex.Message}";
                    throw;
                }

            }
            ViewBag.mensaje = mensaje;

            return View("Resultado", classCalcular);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            ClassCalcular elmininarCalculo = new ClassCalcular();
            using (SqlConnection cn = new SqlConnection(_config["ConnectionStrings:cn"]))
            {
                SqlCommand cmd = new SqlCommand("sp_buscar_cdsblasgalicia @Idcd", cn);
                cmd.Parameters.AddWithValue("@Idcd", id);
                cn.Open();

                using (SqlDataReader dr = cmd.ExecuteReader())
                {
                    if (dr.Read())
                    {
                        elmininarCalculo.Idcd = dr.GetInt32(0);
                        elmininarCalculo.Cliente = dr.GetString(1);
                        elmininarCalculo.CapaDiscoGB = dr.GetInt32(2);
                        elmininarCalculo.CapaCdMB = dr.GetInt32(3);
                        elmininarCalculo.TotalCds = dr.GetInt32(4);

					}

                }
            }
            return View(elmininarCalculo);

        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteCalular(int id)
        {
            string mensaje = "";

            using (SqlConnection cn = new SqlConnection(_config["ConnectionStrings:cn"]))
            {
                try
                {
                    SqlCommand cmd = new SqlCommand("sp_eliminar_cdsblasgalicia", cn);
                    cmd.CommandType = System.Data.CommandType.StoredProcedure;
					cn.Open();

					cmd.Parameters.AddWithValue("@Idcd", id);

                    int c = cmd.ExecuteNonQuery();
                    if (c > 0)
                    {
                        mensaje = $"Registro eliminado correctamente. Filas afectadas: {c}";
                    }
                    else
                    {
                        mensaje = "No se elimino fila. Revisa el procedimiento almacenado.";
                    }
                }
                catch (Exception ex)
                {
                    mensaje = $"Error: {ex.Message}";
                    throw;
                }

            }
            ViewBag.mensaje = mensaje;

            return RedirectToAction("ListadoCalculos");
        }

        public IActionResult Resultado()
        {
            return View();
        }
    }
}

DSW-I_CL2_BLAS_GALICIA_JUAN_RAMIRO/Views/DiscoSolido/Delete.cshtml
@model DSW_I_CL2_BLAS_GALICIA_JUAN_RAMIRO.Models.ClassCalcular

@{
	ViewData["Title"] = "Delete";
	Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<h1>Eliminar Calculo</h1>

<h3>Usted desea eliminar el calculo?</h3>
<div>
	<hr />
	<div class="row justify-content-center">
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Idcd)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Idcd)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Cliente)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Cliente)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.CapaDiscoGB)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.CapaDiscoGB)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.CapaCdMB)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.CapaCdMB)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.TotalCds)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.TotalCds)
		</dd>
	</div>

	<form asp-action="Delete">
		<input type="submit" value="Eliminar Calculo" class="btn btn-danger" /> |
		<a asp-controller="DiscoSolido" asp-action="ListadoCalculos" class="btn btn-primary" style="margin-left: 10px;">Regresar</a>
	</form>
</div>

DSW-I_CL2_BLAS_GALICIA_JUAN_RAMIRO/Views/DiscoSolido/DiscoSolido.cshtml
@{
	ViewBag.Title = "DISCO SOLIDO";
	Layout = "~/Views/Shared/_LayoutMaster.cshtml";

}
@model DSW_I_CL2_BLAS_GALICIA_JUAN_RAMIRO.Models.ClassCalcular

<h1 style="text-align:center">Calcular Capacidad</h1>
<div style="display: flex; justify-content: center; align-items: center;">
	<form asp-controller="DiscoSolido" asp-action="Calcular" method="post" style="width: 300px;">
		<div class="form-group">
			<label for="Cliente" style="display: block; text-align: center;">Cliente</label>
			<input type="text" id="Cliente" name="Cliente" class="form-control" required />
		</div>
		<div class="form-group">
			<label for="CapaDiscoGB" style="display: block; text-align: center;">Capacidad del Disco Duro (GB):</label>
			<input type="number" id="CapaDiscoGB" name="CapaDiscoGB" class="form-control" required />
		</div>
		<br />
		<div style="text-align: center;">
			<button type="submit" class="btn btn-primary">Calcular CDs</button>
			<a asp-controller="DiscoSolido" asp-action="ListadoCalculos" class="btn btn-primary" style="margin-left: 10px;">Ver Listado</a>
		</div>
	</form>
</div>
@* <script>
    document.getElementById("calcularForm").addEventListener("submit", function(event) {
        var cliente = document.getElementById("Cliente").value.trim();
        var capaDiscoGB = document.getElementById("CapaDiscoGB").value.trim();

        if (cliente === "" || capaDiscoGB === "") {
            event.preventDefault();
            alert("Por favor, complete todos los campos antes de calcular.");
        }
    });
</script> *@

DSW-I_CL2_BLAS_GALICIA_JUAN_RAMIRO/Views/DiscoSolido/Edit.cshtml
@model DSW_I_CL2_BLAS_GALICIA_JUAN_RAMIRO.Models.ClassCalcular

@{
	ViewData["Title"] = "Edit";
	Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<h1>Editar Caluclo</h1>

<hr />
<div class="row justify-content-center">
	<div class="col-md-4">
		<form asp-action="Edit">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="Idcd" class="control-label"></label>
				<input asp-for="Idcd" class="form-control" readonly />
				<span asp-validation-for="Idcd" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Cliente" class="control-label"></label>
				<input asp-for="Cliente" class="form-control" />
				<span asp-validation-for="Cliente" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="CapaDiscoGB" class="control-label"></label>
				<input asp-for="CapaDiscoGB" class="form-control" />
				<span asp-validation-for="CapaDiscoGB" class="text-danger"></span>
			</div>
			<div style="text-align:center; margin-top: 20px;">
				@if (!string.IsNullOrEmpty(ViewBag.mensaje))
				{
					<p style="color: green; font-weight: bold;">@ViewBag.mensaje</p>
				}
			</div>
			<br />
			<div class="form-group">
				<input type="submit" value="Editar Calculo" class="btn btn-primary" />
				<a asp-controller="DiscoSolido" asp-action="ListadoCalculos" class="btn btn-primary" style="margin-left: 10px;">Regresar</a>
			</div>
		</form>
	</div>
</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

DSW-I_CL2_BLAS_GALICIA_JUAN_RAMIRO/Views/DiscoSolido/Index.cshtml
<h1 aling="center">
	Disco Solidos de la Mejor Calidad.
</h1>

DSW-I_CL2_BLAS_GALICIA_JUAN_RAMIRO/Views/DiscoSolido/ListadoCalculos.cshtml
@model IEnumerable<DSW_I_CL2_BLAS_GALICIA_JUAN_RAMIRO.Models.ClassCalcular>

@{
	ViewData["Title"] = "ListadoCalculos";
	Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<h1 class="text-center my-4">Listado de Cálculos</h1>

<div>
	<p class="text-center mb-3">
		<a asp-controller="DiscoSolido" asp-action="DiscoSolido" class="btn btn-primary">Registrar nuevo calculo</a>
	</p>
</div>

<div class="table-responsive">
	<table class="table table-striped table-bordered table-hover mx-auto" style="max-width: 1200px;">
		<thead class="thead-dark">
			<tr>
				<th>
					@Html.DisplayNameFor(model => model.Idcd)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.Cliente)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.CapaDiscoGB)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.CapaCdMB)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.TotalCds)
				</th>
				<th>Acciones</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var item in Model)
			{
				<tr>
					<td>
						@Html.DisplayFor(modelItem => item.Idcd)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Cliente)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.CapaDiscoGB)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.CapaCdMB)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.TotalCds)
					</td>
					<td>
						@Html.ActionLink("Editar", "Edit", new { id = item.Idcd }, new { @class = "btn btn-warning", style = "margin-right: 5px;", @role = "button" }) |
						@* @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) | *@
						@Html.ActionLink("Eliminar", "Delete", new { id = item.Idcd }, new { @class = "btn btn-danger", style = "margin-right: 5px;", @role = "button", @id="eliminar"})
					</td>
				</tr>
			}
		</tbody>
	</table>
</div>
<div style="text-align:center; margin-top: 20px;">
	@if (!string.IsNullOrEmpty(ViewBag.mensaje))
	{
		<p style="color: green; font-weight: bold;">@ViewBag.mensaje</p>
	}
</div>
<div style="text-align:center">
	@for (int i = 0; i < (int)ViewBag.paginas; i++)
	{
		@Html.ActionLink((i + 1).ToString(), "ListadoCalculos", "DiscoSolido", new { p = i }, new { @class = "btn btn-primary" })
	}
</div>
@section Scripts {
	<script>
		$(document).ready(function (y) {
			$("tr #eliminar").click(function (y) {
				//evita el reinicio...
				y.preventDefault();
				Swal.fire({
					title: 'Eliminar Registro',
					text: "Usted desea Eliminar el Registro?",
					icon: 'warning',
					showCancelButton: true,
					confirmButtonColor: '#3085d6',
					cancelButtonColor: '#d33',
					confirmButtonText: 'SI, ELIMINAR REGISTRO!',
					cancelButtonText: 'Desea Cancelar?'
				}).then((result) => {
					if (result.isConfirmed) {
						//capturamos el href...(controlador y accion)
						//y lo almacenamos en la variable url...
						var url = $("#eliminar").attr("href");
						//aplicamos ajax
						$.ajax({
							url: url,
							async: true,
							success: function (r) {
								//vemos respuesta del servidor...
								console.log(r);
							}  //fin del success
						})  //fin de ajax...
						setTimeout(function () {
							//tiempo de actualizado de la pagina donde ajax realiza la accion.
							parent.location = "ListadoCalculos"
						}, 1000)  //fin del settimeout........
					}  //fin del if...
				})
			}) // fin del evento click...
		}
	</script>
}
<br />
<div class="text-center mt-4">
	<a asp-controller="DiscoSolido" asp-action="DiscoSolido" class="btn btn-secondary">Regresar</a>
</div>

DSW-I_CL2_BLAS_GALICIA_JUAN_RAMIRO/Views/DiscoSolido/Resultado.cshtml
@{
    ViewBag.Title = "RESULTADO";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

@model DSW_I_CL2_BLAS_GALICIA_JUAN_RAMIRO.Models.ClassCalcular

<h1 style="text-align:center">Respuesta del Cálculo:</h1>

<div style="text-align:center; margin-top: 20px;">
    <p>Para el cliente <strong>@Model.Cliente</strong>:</p>
    <p>Con un disco duro de <strong>@Model.CapaDiscoGB GB</strong> de capacidad de almacenamiento:</p>
    <p>Se necesita un total de <strong>@Model.TotalCds</strong> CDs para hacer una copia de seguridad.</p>
</div>

<div style="text-align:center; margin-top: 20px;">
    @if (!string.IsNullOrEmpty(ViewBag.mensaje))
    {
        <p style="color: green; font-weight: bold;">@ViewBag.mensaje</p>
    }
</div>

<div style="text-align:center; margin-top: 20px;">
    <a asp-controller="DiscoSolido" asp-action="DiscoSolido" class="btn btn-secondary">Regresar</a>
    <a asp-controller="DiscoSolido" asp-action="ListadoCalculos" class="btn btn-primary" style="margin-left: 10px;">Ver Listado</a>
</div>