DSW-I_CL2_BLAS_GALICIA_JUAN_RAMIRO/Controllers/AdaptadorController.cs
using Microsoft.AspNetCore.Mvc;

namespace DSW_I_CL2_BLAS_GALICIA_JUAN_RAMIRO.Controllers
{
    public class AdaptadorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Adaptadores()
        {
            return View();
        }
    }
}

DSW-I_CL2_BLAS_GALICIA_JUAN_RAMIRO/Controllers/MemoriaRamController.cs
using Microsoft.AspNetCore.Mvc;

namespace DSW_I_CL2_BLAS_GALICIA_JUAN_RAMIRO.Controllers
{
    public class MemoriaRamController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult MemoRam()
        {
            return View();
        }
    }
}

DSW-I_CL2_BLAS_GALICIA_JUAN_RAMIRO/Controllers/PerifericoController.cs
using Microsoft.AspNetCore.Mvc;

namespace DSW_I_CL2_BLAS_GALICIA_JUAN_RAMIRO.Controllers
{
    public class PerifericoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Perifericos()
        {
            return View();
        }
    }
}

DSW-I_CL2_BLAS_GALICIA_JUAN_RAMIRO/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DSW_I_CL2_BLAS_GALICIA_JUAN_RAMIRO</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DSW_I_CL2_BLAS_GALICIA_JUAN_RAMIRO.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DSW_I_CL2_BLAS_GALICIA_JUAN_RAMIRO</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DSW_I_CL2_BLAS_GALICIA_JUAN_RAMIRO - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DSW-I_CL2_BLAS_GALICIA_JUAN_RAMIRO/Views/Shared/_LayoutMaster.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Estilos.css" asp-append-version="true" />
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
    <header>
        <img class="logo" src="~/img/banner.jpg" />
    </header>

    <nav>
        <div class="menu">
            <a href="@Url.Action("Index", "Home")" class="menu-item">Inicio</a>
            <a href="@Url.Action("DiscoSolido", "DiscoSolido")" class="menu-item">Disco Solido</a>
            <a href="@Url.Action("MemoRam", "MemoriaRam")" class="menu-item">Memorias Ram</a>
            <a href="@Url.Action("Perifericos", "Periferico")" class="menu-item">Periféricos</a>
            <a href="@Url.Action("Adaptadores", "Adaptador")" class="menu-item">Adaptadores</a>
        </div>
    </nav>
    <div>
        @RenderBody()
    </div>
    <footer>
        <div>
            SOFTWARELIMA S.A.C <br />
            Av. arequipa - lima 1128 - peru <br />
            Telefono: 57897629 <br />
            Mail: laboPeru@hotmail.com <br />
        </div>
        <div class="footer-rs">
            <img src="~/img/Facebook.jpg" class="rs" />
            <img src="~/img/twitter.jpg" class="rs" />
            <img src="~/img/whatsapp.jpg" class="rs" />
            <img src="~/img/youtube.jpg" class="rs" />
        </div>
    </footer>
    @RenderSection("scripts", required:false)
</body>
</html>